name: "Pull Request Code Review Bot"
description: "A bot that performs code reviews"
author: "Your Name"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  color: "blue"
  icon: "gift"
  name: "Code Review Bot"
inputs:
  github-token:
    description: "GitHub token for authentication"
    required: true
