services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "8001:8001"
      - "11434:11434"
    volumes:
      - ./data:/root/.ollama
    restart: unless-stopped # 서비스가 실패 시 재시작
